CREATE TABLE WIS.MAPSKLK (
	STIMMKREIS INT,
	LANDKREIS_PLZ INT,
	JAHR INT,
	PRIMARY KEY (STIMMKREIS));

CREATE TABLE WIS.STATISTIK_STERBERATE (
	LANDKREIS NVARCHAR(38),
	LANDKREIS_PLZ INT,
	STERBERATE FLOAT,
	PRIMARY KEY (LANDKREIS_PLZ));

CREATE TABLE WIS.STATISTIK_GEHALT (
	LANDKREIS NVARCHAR(38),
	LANDKREIS_PLZ INT,
	GEHALT INT,
	PRIMARY KEY (LANDKREIS_PLZ));
