stages:
- name: build
- name: deploy
  if: branch = master AND type = push

jobs:
  include:
  - stage: build
    name: "Build Frontend"
    language: node_js
    before_install:
    - cd WIS/web
    script:
    - npm build

  - stage: build
    name: "Build Backend"
    language: rust
    rust: nightly
    before_install:
    - cd WIS/backend

  - stage: deploy
    name: "Deploy Backend Docker image"
    services: docker
    before_script:
    - cd WIS/backend
    script:
    - docker build -t wis-backend .
    before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    deploy:
      provider: script
      script: docker push
      on:
        branch: master
    after_deploy:
    - curl "$DEPLOYMENT_TRIGGER_URL"

  - stage: deploy
    name: "Deploy Frontend Docker image"
    services: docker
    before_script:
    - cd WIS/web
    script:
    - docker build -t wis-frontend .
    before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    deploy:
      provider: script
      script: docker push
      on:
        branch: master
    after_deploy:
    - curl "$DEPLOYMENT_TRIGGER_URL"
