stages:
- name: build
- name: deploy
  if: branch = deploy/azure AND type = push

jobs:
  include:
  - stage: build
    name: "Build Frontend"
    language: node_js
    before_install:
    - cd WIS/web
    script:
    - npm build

  - stage: build
    name: "Build Backend"
    language: rust
    rust: nightly
    before_install:
    - cd WIS/backend

  - stage: deploy
    name: "Deploy Backend Docker image"
    services: docker
    before_script:
    - cd WIS/backend
    script:
    - docker build -t dbprojekt.azurecr.io/wis-backend --build-arg BUILD_VERSION="Commit $TRAVIS_COMMIT on branch '$TRAVIS_BRANCH'" .
    before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin dbprojekt.azurecr.io
    deploy:
      provider: script
      script: docker push dbprojekt.azurecr.io/wis-backend
      on:
        branch: deploy/azure
    after_deploy:
    - curl "$DEPLOYMENT_TRIGGER_URL"

  - stage: deploy
    name: "Deploy Frontend Docker image"
    services: docker
    before_script:
    - cd WIS/web
    script:
    - docker build -t dbprojekt.azurecr.io/wis-frontend --build-arg BUILD_VERSION="Commit $TRAVIS_COMMIT on branch '$TRAVIS_BRANCH'" .
    before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin dbprojekt.azurecr.io
    deploy:
      provider: script
      script: docker push dbprojekt.azurecr.io/wis-frontend
      on:
        branch: deploy/azure
    after_deploy:
    - curl "$DEPLOYMENT_TRIGGER_URL"
