CREATE PROCEDURE WIS.GET_STIMMKREISE (IN _jahr INT, 
OUT _out TABLE (
    NR INT,
    NAME NVARCHAR(47),
    STIMMBERECHTIGTE INT,
    WAHLKREIS VARCHAR(13),
    WAHLKREISNR INT)) 
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
READS SQL DATA WITH RESULT VIEW PROC_STIMMKREISE AS
BEGIN

_out = SELECT S.NR, S.NAME, S.STIMMBERECHTIGTE, W.NAME AS WAHLKREIS, W.NR AS WAHLKREISNR
FROM WIS.STIMMKREIS S JOIN WIS.WAHLKREIS W ON S.WAHLKREIS=W.NR
WHERE S.JAHR=:_jahr;

END;
