/*
 * Gibt die Wahlbeteiligung für einen Stimmkreis für ein Jahr zurück.
 * Die Wahlbeteiligung ist dabei nicht trivial auszurechnen, da man nicht
 * genau weiß, ob eine Person beide Stimmzettel, oder nur eine Erst- oder Zweitstimme
 * abgegeben hat. Als Annäherung nehmen wir hier den MAX Wert der jeweiligen Anzahl.
 */
CREATE PROCEDURE WIS.GET_WAHLBETEILIGUNG (IN _perform_on_aggregates BOOLEAN, IN _jahr INT, IN _stimmkreis INT,
OUT _out TABLE (
    WAHLBETEILIGUNG N_DOUBLE)) 
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
READS SQL DATA WITH RESULT VIEW PROC_WAHLBETEILIGUNG AS
BEGIN

_out = 

WITH ANZAHLERSTSTIMMEN AS (
SELECT E.STIMMKREIS, E.JAHR, COUNT(*) AS ANZAHL 
FROM WIS.ERSTSTIMME E
WHERE E.STIMMKREIS=:_stimmkreis AND E.JAHR=:_jahr
GROUP BY E.STIMMKREIS, E.JAHR),

ANZAHLZWEITSTIMMEN AS (
SELECT STIMMKREIS, JAHR, SUM(ANZAHL_TMP) AS ANZAHL 
FROM (
    SELECT ZP.STIMMKREIS, ZP.JAHR, COUNT(*) AS ANZAHL_TMP
    FROM WIS.ZWEITSTIMMEPARTEI ZP
    WHERE ZP.STIMMKREIS=:_stimmkreis AND ZP.JAHR=:_jahr
    GROUP BY ZP.STIMMKREIS, ZP.JAHR
    UNION ALL
    SELECT ZK.STIMMKREIS, ZK.JAHR, COUNT(*) AS ANZAHL_TMP
    FROM WIS.ZWEITSTIMMEKANDIDAT ZK
    WHERE ZK.STIMMKREIS=:_stimmkreis AND ZK.JAHR=:_jahr
    GROUP BY ZK.STIMMKREIS, ZK.JAHR)
GROUP BY STIMMKREIS, JAHR),

WAEHLER AS (
SELECT STIMMKREIS, JAHR, MAX(ANZAHL) AS ANZAHL
FROM (
    SELECT * FROM ANZAHLERSTSTIMMEN
    UNION ALL
    SELECT * FROM ANZAHLZWEITSTIMMEN)
GROUP BY STIMMKREIS, JAHR)

SELECT W.ANZAHL / SK.STIMMBERECHTIGTE * 100 AS WAHLBETEILIGUNG
FROM WIS.STIMMKREIS SK JOIN WAEHLER W ON SK.JAHR=W.JAHR AND SK.NR=W.STIMMKREIS;

END;
