CREATE PROCEDURE WIS.GET_SIEGERPARTEI_ZWEITSTIMMEN (IN _perform_on_aggregates BOOLEAN, IN _jahr INT, IN _stimmkreis INT,
OUT _out TABLE (
    PARTEI NVARCHAR(20),
    ANZAHLZWEITSTIMMEN INT)) 
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
READS SQL DATA WITH RESULT VIEW PROC_SIEGERPARTEI_ZWEITSTIMMEN AS
BEGIN

_out = 
WITH AGGREGATPARTEISTIMMEN AS (
SELECT PARTEI, JAHR, STIMMKREIS, COUNT(*) AS ANZAHLGESAMTZWEITSTIMMEN
FROM (
    SELECT STIMMKREIS, JAHR, PARTEI
    FROM WIS.ZWEITSTIMMEPARTEI ZSP
    WHERE ZSP.JAHR=:_jahr AND ZSP.STIMMKREIS=:_stimmkreis
    UNION ALL
    SELECT ZS.STIMMKREIS, ZS.JAHR, K.PARTEI
    FROM WIS.ZWEITSTIMMEKANDIDAT ZS JOIN WIS.KANDIDAT K ON ZS.KANDIDAT=K.ID AND ZS.JAHR=K.JAHR
    WHERE ZS.JAHR=:_jahr AND ZS.STIMMKREIS=:_stimmkreis
) GROUP BY STIMMKREIS, JAHR, PARTEI),


/*
 * Gibt für jeden Stimmkreis die Anzahl der Zweitstimmen der Gewinnerpartei an. Dieser Wert wird dann
 * verwendet, um die tatsächliche Gewinnerpartei zu finden.
 */
MAXANZAHLZWEITSTIMMEN AS (
SELECT GES.JAHR, GES.STIMMKREIS, MAX(GES.ANZAHLGESAMTZWEITSTIMMEN) AS MAXSTIMMEN
FROM AGGREGATPARTEISTIMMEN GES
GROUP BY GES.JAHR, GES.STIMMKREIS)

SELECT P.ABKUERZUNG AS PARTEI, GES.ANZAHLGESAMTZWEITSTIMMEN AS ANZAHLZWEITSTIMMEN
FROM AGGREGATPARTEISTIMMEN GES JOIN MAXANZAHLZWEITSTIMMEN M ON GES.JAHR=M.JAHR AND GES.STIMMKREIS=M.STIMMKREIS
    JOIN WIS.PARTEI P ON GES.PARTEI=P.ID
WHERE GES.ANZAHLGESAMTZWEITSTIMMEN=M.MAXSTIMMEN


END;
