CREATE TRIGGER WIS.UPDATE_AGGREGATES_ZWEITSTIMMEPARTEI AFTER INSERT
ON WIS.ZWEITSTIMMEPARTEI REFERENCING NEW ROW AS _new
FOR EACH ROW
BEGIN

DECLARE _aggregate_entry_exists INT;

SELECT COUNT(*) INTO _aggregate_entry_exists FROM WIS.AGGREGAT_ZWEITSTIMMEPARTEI AGG
WHERE AGG.PARTEI=:_new.PARTEI AND AGG.STIMMKREIS=:_new.STIMMKREIS AND AGG.JAHR=:_new.JAHR;

IF (:_aggregate_entry_exists > 0)
THEN
    UPDATE WIS.AGGREGAT_ZWEITSTIMMEPARTEI SET STIMMEN=STIMMEN+1
    WHERE PARTEI=:_new.PARTEI AND STIMMKREIS=:_new.STIMMKREIS AND JAHR=:_new.JAHR;
ELSE
    INSERT INTO WIS.AGGREGAT_ZWEITSTIMMEPARTEI VALUES (:_new.PARTEI, :_new.STIMMKREIS, :_new.JAHR, 1);
END IF;

END;
