CREATE TRIGGER WIS.UPDATE_AGGREGATES_ERSTSTIMME AFTER INSERT
ON WIS.ERSTSTIMME REFERENCING NEW ROW AS _new
FOR EACH ROW
BEGIN

DECLARE _aggregate_entry_exists INT;

SELECT COUNT(*) INTO _aggregate_entry_exists FROM WIS.AGGREGAT_ERSTSTIMME AGG
WHERE AGG.KANDIDAT=:_new.KANDIDAT AND AGG.STIMMKREIS=:_new.STIMMKREIS AND AGG.JAHR=:_new.JAHR;

IF (:_aggregate_entry_exists > 0)
THEN
    UPDATE WIS.AGGREGAT_ERSTSTIMME SET STIMMEN=STIMMEN+1
    WHERE KANDIDAT=:_new.KANDIDAT AND STIMMKREIS=:_new.STIMMKREIS AND JAHR=:_new.JAHR;
ELSE
    INSERT INTO WIS.AGGREGAT_ERSTSTIMME VALUES (:_new.KANDIDAT, :_new.STIMMKREIS, :_new.JAHR, 1);
END IF;

END;
