SELECT P.NAME AS PARTEI, P.ABKUERZUNG AS PARTEI_ABKUERZUNG, P.ID AS PARTEI_ID, K.VORNAME AS KANDIDAT_VORNAME, K.NACHNAME AS KANDIDAT_NACHNAME, K.ID AS KANDIDAT_ID, WZE.KANDIDATPOS AS LISTENPOSITION
FROM WIS.WAHLZETTEL_ERSTSTIMME WZE JOIN WIS.KANDIDAT K ON WZE.KANDIDAT=K.ID AND WZE.JAHR=K.JAHR
    JOIN WIS.PARTEI P ON K.PARTEI=P.ID
WHERE WZE.STIMMKREIS=? AND WZE.JAHR=?
ORDER BY WZE.KANDIDATPOS
