WITH AGGREGATKANDIDATERSTSTIMMEN AS (
SELECT K.ID AS KANDIDAT, S.JAHR AS JAHR, COUNT(*) AS ANZAHLERSTSTIMMEN, S.STIMMKREIS AS STIMMKREIS
FROM WIS.ERSTSTIMME S JOIN WIS.KANDIDAT K ON S.KANDIDAT=K.ID
GROUP BY K.ID, S.JAHR, S.STIMMKREIS),

AGGREGATPARTEISTIMMEN AS (
SELECT PARTEI, JAHR, STIMMKREIS, COUNT(*) AS ANZAHLGESAMTZWEITSTIMMEN
FROM (
    SELECT STIMMKREIS, JAHR, PARTEI
    FROM WIS.ZWEITSTIMMEPARTEI ZSP
    UNION ALL
    SELECT ZS.STIMMKREIS, ZS.JAHR, K.PARTEI
    FROM WIS.ZWEITSTIMMEKANDIDAT ZS JOIN WIS.KANDIDAT K ON ZS.KANDIDAT=K.ID AND ZS.JAHR=K.JAHR
) GROUP BY STIMMKREIS, JAHR, PARTEI),


/*
 * Errechnet für jede Partei die Gesamtzahl der Stimmen für einen Stimmkreis in einem Jahr.
 * Dabei werden Erst- und Zweitstimmen für eine Partei addiert.
 * JAHR, STIMMKREIS, PARTEI, STIMMEN
 */
GESAMTSTIMMENPARTEI AS (
SELECT JAHR, STIMMKREIS, PARTEI, SUM(STIMMEN) AS STIMMEN
FROM (
    SELECT PARTEI, KS.JAHR AS JAHR, STIMMKREIS, ANZAHLERSTSTIMMEN AS STIMMEN
    FROM AGGREGATKANDIDATERSTSTIMMEN KS JOIN WIS.KANDIDAT K ON KS.JAHR=K.JAHR AND KS.KANDIDAT=K.ID
    UNION ALL
    SELECT PARTEI, JAHR, STIMMKREIS, ANZAHLGESAMTZWEITSTIMMEN AS STIMMEN
    FROM AGGREGATPARTEISTIMMEN PS
) WHERE STIMMKREIS=? AND JAHR=?
GROUP BY PARTEI, JAHR, STIMMKREIS),

/*
 * Errechnet die Gesamtzahl an abgegebenen Stimmen für einen Stimmkreis in einem Jahr.
 * Dabei zählen sowohl Erst- als auch Zweitstimmen in das Ergebnis mit ein.
 * JAHR, STIMMKREIS, STIMMEN
 */
STIMMKREISGESAMTSTIMMEN AS (
SELECT JAHR, STIMMKREIS, SUM(STIMMEN) AS STIMMEN
FROM GESAMTSTIMMENPARTEI
GROUP BY JAHR, STIMMKREIS),

/*
 * Berechnet für jede Partei die absolute Anzahl an Stimmen und die Verteilung der Stimmen
 * auf die einzelnen Parteien pro Stimmkreis in einem Wahljahr.
 * JAHR, STIMMKREIS, PARTEI, STIMMENABSOLUT, STIMMENRELATIV
 */
STATISTIK AS (
SELECT P.JAHR AS JAHR, P.STIMMKREIS AS STIMMKREIS, PARTEI, P.STIMMEN AS STIMMENABSOLUT, P.STIMMEN * 100 / GS.STIMMEN AS STIMMENRELATIV
FROM GESAMTSTIMMENPARTEI P JOIN STIMMKREISGESAMTSTIMMEN GS ON P.JAHR=GS.JAHR AND P.STIMMKREIS=GS.STIMMKREIS)

/*
 * Gibt das Ergebnis von STATISTIK mit sinnvollen Feldern aus und ersetzt IDs durch Namen.
 * PARTEI(Kürzel), GESAMTSTIMMEN, PROZENT
 */
SELECT P.ABKUERZUNG AS PARTEI, P.FARBE AS PARTEI_FARBE, STIMMENABSOLUT AS GESAMTSTIMMEN, STIMMENRELATIV AS PROZENT
FROM STATISTIK S JOIN WIS.PARTEI P
ON S.PARTEI=P.ID
ORDER BY S.STIMMENABSOLUT DESC
