/*
 * Berechnet das Ergebnis für die Parteien im Jahr 2013.
 * Sowohl absolute Anzahl an Stimmen als auch die relative Verteilung der Stimmen auf die Parteien.
 * Vergleiche @file/stimmkreis-parteiergebnis.sql
 *
 * Hier werden für den direkten Vergleicht die IDs der Stimmkreise an die IDs von 2018 angeglichen,
 * da 2018 der Stimmkreis 109 dazugekommen ist und somit alle IDs in Oberbayern ab 109 um 1 verrutschen.
 */
WITH AGGREGATKANDIDATERSTSTIMMEN_2013 AS (
SELECT K.ID AS KANDIDAT, S.JAHR AS JAHR, COUNT(*) AS ANZAHLERSTSTIMMEN, S.STIMMKREIS AS STIMMKREIS
FROM WIS.ERSTSTIMME S JOIN WIS.KANDIDAT K ON S.KANDIDAT=K.ID
WHERE S.JAHR=2013 AND S.STIMMKREIS=CASE WHEN {{STIMMKREIS}}>109 AND {{STIMMKREIS}}<199 THEN {{STIMMKREIS}}-1 WHEN {{STIMMKREIS}}=109 THEN 0/*NO MATCH*/ ELSE {{STIMMKREIS}} END
GROUP BY K.ID, S.JAHR, S.STIMMKREIS),

AGGREGATPARTEISTIMMEN_2013 AS (
SELECT PARTEI, JAHR, STIMMKREIS, COUNT(*) AS ANZAHLGESAMTZWEITSTIMMEN
FROM (
    SELECT STIMMKREIS, JAHR, PARTEI
    FROM WIS.ZWEITSTIMMEPARTEI ZSP
    WHERE ZSP.JAHR=2013 AND ZSP.STIMMKREIS=CASE WHEN {{STIMMKREIS}}>109 AND {{STIMMKREIS}}<199 THEN {{STIMMKREIS}}-1 WHEN {{STIMMKREIS}}=109 THEN 0/*NO MATCH*/ ELSE {{STIMMKREIS}} END
    UNION ALL
    SELECT ZS.STIMMKREIS, ZS.JAHR, K.PARTEI
    FROM WIS.ZWEITSTIMMEKANDIDAT ZS JOIN WIS.KANDIDAT K ON ZS.KANDIDAT=K.ID AND ZS.JAHR=K.JAHR
    WHERE ZS.JAHR=2013 AND ZS.STIMMKREIS=CASE WHEN {{STIMMKREIS}}>109 AND {{STIMMKREIS}}<199 THEN {{STIMMKREIS}}-1 WHEN {{STIMMKREIS}}=109 THEN 0/*NO MATCH*/ ELSE {{STIMMKREIS}} END
) GROUP BY STIMMKREIS, JAHR, PARTEI),


GESAMTSTIMMENPARTEI_2013 AS (
SELECT JAHR, STIMMKREIS, PARTEI, SUM(STIMMEN) AS STIMMEN
FROM (
    SELECT PARTEI, KS.JAHR AS JAHR, STIMMKREIS, ANZAHLERSTSTIMMEN AS STIMMEN
    FROM AGGREGATKANDIDATERSTSTIMMEN_2013 KS JOIN WIS.KANDIDAT K ON KS.JAHR=K.JAHR AND KS.KANDIDAT=K.ID
    UNION ALL
    SELECT PARTEI, JAHR, STIMMKREIS, ANZAHLGESAMTZWEITSTIMMEN AS STIMMEN
    FROM AGGREGATPARTEISTIMMEN_2013 PS
) GROUP BY PARTEI, JAHR, STIMMKREIS),

STIMMKREISGESAMTSTIMMEN_2013 AS (
SELECT JAHR, STIMMKREIS, SUM(STIMMEN) AS STIMMEN
FROM GESAMTSTIMMENPARTEI_2013
GROUP BY JAHR, STIMMKREIS),

STATISTIK_2013 AS (
SELECT P.JAHR AS JAHR, P.STIMMKREIS AS STIMMKREIS, PARTEI, P.STIMMEN AS STIMMENABSOLUT, P.STIMMEN * 100 / GS.STIMMEN AS STIMMENRELATIV
FROM GESAMTSTIMMENPARTEI_2013 P JOIN STIMMKREISGESAMTSTIMMEN_2013 GS ON P.JAHR=GS.JAHR AND P.STIMMKREIS=GS.STIMMKREIS),





/*
 * Berechnet das Ergebnis für die Parteien im Jahr 2018.
 * Sowohl absolute Anzahl an Stimmen als auch die relative Verteilung der Stimmen auf die Parteien.
 * Vergleiche @file/stimmkreis-parteiergebnis.sql
 */
AGGREGATKANDIDATERSTSTIMMEN_2018 AS (
SELECT K.ID AS KANDIDAT, S.JAHR AS JAHR, COUNT(*) AS ANZAHLERSTSTIMMEN, S.STIMMKREIS AS STIMMKREIS
FROM WIS.ERSTSTIMME S JOIN WIS.KANDIDAT K ON S.KANDIDAT=K.ID
WHERE S.STIMMKREIS={{STIMMKREIS}} AND S.JAHR=2018
GROUP BY K.ID, S.JAHR, S.STIMMKREIS),

AGGREGATPARTEISTIMMEN_2018 AS (
SELECT PARTEI, JAHR, STIMMKREIS, COUNT(*) AS ANZAHLGESAMTZWEITSTIMMEN
FROM (
    SELECT STIMMKREIS, JAHR, PARTEI
    FROM WIS.ZWEITSTIMMEPARTEI ZSP
    WHERE ZSP.JAHR=2018 AND ZSP.STIMMKREIS={{STIMMKREIS}}
    UNION ALL
    SELECT ZS.STIMMKREIS, ZS.JAHR, K.PARTEI
    FROM WIS.ZWEITSTIMMEKANDIDAT ZS JOIN WIS.KANDIDAT K ON ZS.KANDIDAT=K.ID AND ZS.JAHR=K.JAHR
    WHERE ZS.JAHR=2018 AND ZS.STIMMKREIS={{STIMMKREIS}}
) GROUP BY STIMMKREIS, JAHR, PARTEI),


GESAMTSTIMMENPARTEI_2018 AS (
SELECT JAHR, STIMMKREIS, PARTEI, SUM(STIMMEN) AS STIMMEN
FROM (
    SELECT PARTEI, KS.JAHR AS JAHR, STIMMKREIS, ANZAHLERSTSTIMMEN AS STIMMEN
    FROM AGGREGATKANDIDATERSTSTIMMEN_2018 KS JOIN WIS.KANDIDAT K ON KS.JAHR=K.JAHR AND KS.KANDIDAT=K.ID
    UNION ALL
    SELECT PARTEI, JAHR, STIMMKREIS, ANZAHLGESAMTZWEITSTIMMEN AS STIMMEN
    FROM AGGREGATPARTEISTIMMEN_2018 PS
) GROUP BY PARTEI, JAHR, STIMMKREIS),

STIMMKREISGESAMTSTIMMEN_2018 AS (
SELECT JAHR, STIMMKREIS, SUM(STIMMEN) AS STIMMEN
FROM GESAMTSTIMMENPARTEI_2018
GROUP BY JAHR, STIMMKREIS),

STATISTIK_2018 AS (
SELECT P.JAHR AS JAHR, P.STIMMKREIS AS STIMMKREIS, PARTEI, P.STIMMEN AS STIMMENABSOLUT, P.STIMMEN * 100 / GS.STIMMEN AS STIMMENRELATIV
FROM GESAMTSTIMMENPARTEI_2018 P JOIN STIMMKREISGESAMTSTIMMEN_2018 GS ON P.JAHR=GS.JAHR AND P.STIMMKREIS=GS.STIMMKREIS)




/*
 * Vergleicht die Ergebnisse für die Parteien aus dem Jahr 2013 mit denen aus dem Jahr 2018.
 * Parteien, die nicht mehr 2018 angetreten sind, fallen aus dem Ergebnis heraus.
 * Parteien, die nur 2018 angetreten sind, erhalten ihr Ergebnis als "Änderung".
 */
SELECT P.ABKUERZUNG AS PARTEI, P.FARBE AS PARTEI_FARBE, S18.STIMMENABSOLUT - COALESCE(S13.STIMMENABSOLUT, 0) AS DIFF_GESAMTSTIMMEN, S18.STIMMENRELATIV - COALESCE(S13.STIMMENRELATIV, 0) AS DIFF_PROZENT
FROM STATISTIK_2018 S18 LEFT OUTER JOIN STATISTIK_2013 S13 ON S18.PARTEI=S13.PARTEI
     JOIN WIS.PARTEI P ON S18.PARTEI=P.ID
ORDER BY S18.STIMMENABSOLUT DESC
