/*
 * Berechnet die Verteilung der Stimmen aller Parteien in ganz Bayern.
 * Dabei zählen Erst- und Zweitstimmen gleich.
 */


WITH AGGREGATKANDIDATERSTSTIMMEN AS (
SELECT K.ID AS KANDIDAT, S.JAHR AS JAHR, COUNT(*) AS ANZAHLERSTSTIMMEN
FROM WIS.ERSTSTIMME S JOIN WIS.KANDIDAT K ON S.KANDIDAT=K.ID
WHERE S.JAHR={{JAHR}}
GROUP BY K.ID, S.JAHR),

AGGREGATPARTEISTIMMEN AS (
SELECT PARTEI, JAHR, COUNT(*) AS ANZAHLGESAMTZWEITSTIMMEN
FROM (
    SELECT JAHR, PARTEIID AS PARTEI
    FROM WIS.ZWEITSTIMMEPARTEI ZSP
    WHERE ZSP.JAHR={{JAHR}}
    UNION ALL
    SELECT ZS.JAHR, K.PARTEI
    FROM WIS.ZWEITSTIMMEKANDIDAT ZS JOIN WIS.KANDIDAT K ON ZS.KANDIDAT=K.ID AND ZS.JAHR=K.JAHR
    WHERE ZS.JAHR={{JAHR}}
) GROUP BY JAHR, PARTEI),


/*
 * Errechnet für jede Partei die Gesamtzahl der Stimmen in ganz Bayern.
 * Dabei werden Erst- und Zweitstimmen für eine Partei addiert.
 * JAHR, PARTEI, STIMMEN
 */
GESAMTSTIMMENPARTEI AS (
SELECT JAHR, PARTEI, SUM(STIMMEN) AS STIMMEN
FROM (
    SELECT PARTEI, KS.JAHR AS JAHR, ANZAHLERSTSTIMMEN AS STIMMEN
    FROM AGGREGATKANDIDATERSTSTIMMEN KS JOIN WIS.KANDIDAT K ON KS.JAHR=K.JAHR AND KS.KANDIDAT=K.ID
    UNION ALL
    SELECT PARTEI, JAHR, ANZAHLGESAMTZWEITSTIMMEN AS STIMMEN
    FROM AGGREGATPARTEISTIMMEN PS
) GROUP BY PARTEI, JAHR),


/*
 * Errechnet die Gesamtzahl an abgegebenen Stimmen für ganz Bayern in einem Jahr.
 * Dabei zählen sowohl Erst- als auch Zweitstimmen in das Ergebnis mit ein.
 * JAHR, STIMMEN
 */
GESAMTSTIMMEN AS (
SELECT JAHR, SUM(STIMMEN) AS STIMMEN
FROM GESAMTSTIMMENPARTEI
GROUP BY JAHR),


/*
 * Berechnet für jede Partei die absolute Anzahl an Stimmen und die Verteilung der Stimmen
 * auf die einzelnen Parteien in ganz Bayern in einem Wahljahr.
 * JAHR, PARTEI, STIMMENABSOLUT, STIMMENRELATIV
 */
STATISTIK AS (
SELECT P.JAHR AS JAHR, PARTEI, P.STIMMEN AS STIMMENABSOLUT, P.STIMMEN * 100 / GS.STIMMEN AS STIMMENRELATIV
FROM GESAMTSTIMMENPARTEI P JOIN GESAMTSTIMMEN GS ON P.JAHR=GS.JAHR)

/*
 * Gibt das Ergebnis von STATISTIK mit sinnvollen Feldern aus und ersetzt IDs durch Namen.
 * PARTEI(Kürzel), GESAMTSTIMMEN, PROZENT
 */
SELECT P.ABKUERZUNG AS PARTEI, STIMMENABSOLUT AS GESAMTSTIMMEN, STIMMENRELATIV AS PROZENT
FROM STATISTIK S JOIN WIS.PARTEI P
ON S.PARTEI=P.ID
ORDER BY S.STIMMENABSOLUT DESC
