DECLARE JAHR_AKTUELL INTEGER := 2013;
DECLARE STIMMKREIS_AKTUELL INTEGER := 1;

WITH ZWEITSTIMMENGEWINNER_HELP AS (
SELECT STIMMKREISNR, JAHR, MAX(ANZAHLGESAMTZWEITSTIMMEN) AS MAXIMUM
FROM AGGREGATPARTEISTIMMEN
GROUP BY STIMMKREISNR, JAHR)

SELECT A.PARTEIID
FROM AGGREGATPARTEISTIMMEN A JOIN ZWEITSTIMMENGEWINNER_HELP Z ON ((A.STIMMKREISNR = Z.STIMMKREISNR) AND (A.JAHR = Z.JAHR) AND (A.ANZAHLGESAMTZWEITSTIMMEN = Z.MAXIMUM))
WHERE (STIMMKREISNR = STIMMKREIS_AKTUELL) AND (JAHR = JAHR_AKTUELL)
