/*
 * Gibt die Wahlbeteiligung für einen Stimmkreis für ein Jahr zurück.
 * Die Wahlbeteiligung ist dabei nicht trivial auszurechnen, da man nicht
 * genau weiß, ob eine Person beide Stimmzettel, oder nur eine Erst- oder Zweitstimme
 * abgegeben hat. Als Annäherung nehmen wir hier den MAX Wert der jeweiligen Anzahl.
 */

WITH ANZAHLERSTSTIMMEN AS (
SELECT E.STIMMKREIS, E.JAHR, COUNT(*) AS ANZAHL 
FROM WIS.ERSTSTIMME E
WHERE E.STIMMKREIS={{STIMMKREIS}} AND E.JAHR={{JAHR}}
GROUP BY E.STIMMKREIS, E.JAHR),

ANZAHLZWEITSTIMMEN AS (
SELECT STIMMKREIS, JAHR, SUM(ANZAHL_TMP) AS ANZAHL 
FROM (
    SELECT ZP.STIMMKREIS, ZP.JAHR, COUNT(*) AS ANZAHL_TMP
    FROM WIS.ZWEITSTIMMEPARTEI ZP
    WHERE ZP.STIMMKREIS={{STIMMKREIS}} AND ZP.JAHR={{JAHR}}
    GROUP BY ZP.STIMMKREIS, ZP.JAHR
    UNION ALL
    SELECT ZK.STIMMKREIS, ZK.JAHR, COUNT(*) AS ANZAHL_TMP
    FROM WIS.ZWEITSTIMMEKANDIDAT ZK
    WHERE ZK.STIMMKREIS={{STIMMKREIS}} AND ZK.JAHR={{JAHR}}
    GROUP BY ZK.STIMMKREIS, ZK.JAHR)
GROUP BY STIMMKREIS, JAHR),

WAEHLER AS (
SELECT STIMMKREIS, JAHR, MAX(ANZAHL) AS ANZAHL
FROM (
    SELECT * FROM ANZAHLERSTSTIMMEN
    UNION ALL
    SELECT * FROM ANZAHLZWEITSTIMMEN)
GROUP BY STIMMKREIS, JAHR)

SELECT W.ANZAHL / SK.STIMMBERECHTIGTE * 100 AS WAHLBETEILIGUNG
FROM WIS.STIMMKREIS SK JOIN WAEHLER W ON SK.JAHR=W.JAHR AND SK.NR=W.STIMMKREIS
