WITH AGGREGATKANDIDATERSTSTIMMEN AS (
SELECT K.ID AS KANDIDAT, S.JAHR AS JAHR, COUNT(*) AS ANZAHLERSTSTIMMEN,  AS STIMMKREIS
FROM WIS.ERSTSTIMME S JOIN WIS.KANDIDAT K ON S.KANDIDAT=K.ID 
GROUP BY K.ID, S.JAHR),

AGGREGATPARTEISTIMMEN AS (
SELECT PARTEI, JAHR, STIMMKREIS, COUNT(*) AS ANZAHLGESAMTZWEITSTIMMEN
FROM (
    SELECT STIMMKREIS, JAHR, PARTEIID AS PARTEI
    FROM WIS.ZWEITSTIMMEPARTEI
    UNION ALL
    SELECT ZS.STIMMKREIS, ZS.JAHR, K.PARTEI
    FROM WIS.ZWEITSTIMMEKANDIDAT ZS JOIN WIS.KANDIDAT K ON ZS.KANDIDAT=K.ID
) GROUP BY STIMMKREIS, JAHR, PARTEI),

WAHLKREISGESAMTSTIMMEN_HELP AS (
SELECT W.JAHR AS JAHR, W.NR AS WAHLKREIS, S.NR AS STIMMKREIS, AK.KANDIDAT AS KANDIDAT, AK.ANZAHLERSTSTIMMEN AS ERSTSTIMMEN, K.PARTEI AS PARTEI, AP.ANZAHLGESAMTZWEITSTIMMEN AS ZWEITSTIMMEN
FROM (((WIS.WAHLKREIS W JOIN WIS.STIMMKREIS S ON ((W.JAHR = S.JAHR) AND (W.NR = S.WAHLKREIS))) JOIN AGGREGATKANDIDATERSTSTIMMEN AK ON ((AK.JAHR = S.JAHR) AND (AK.STIMMKREIS = S.NR))) JOIN WIS.KANDIDAT K ON ((K.ID = AK.KANDIDAT) AND (K.JAHR = AK.JAHR))) JOIN AGGREGATPARTEISTIMMEN AP ON ((AP.JAHR = S.JAHR) AND (AP.STIMMKREIS = S.NR) AND (AP.PARTEI = K.PARTEI))),

WAHLKREISGESAMTSTIMMEN AS (
SELECT WAHLKREIS, JAHR, (SUM(ZWEITSTIMMEN) + SUM(ERSTSTIMMEN)) AS GESAMTSTIMMEN
FROM  WAHLKREISGESAMTSTIMMEN_HELP
GROUP BY WAHLKREIS, JAHR),

WAHLKREISPARTEIGESAMTSTIMMEN AS (
SELECT WAHLKREIS, JAHR, PARTEI, (SUM(ZWEITSTIMMEN)+SUM(ERSTSTIMMEN)) AS PARTEIGESAMTSTIMMEN
FROM WAHLKREISGESAMTSTIMMEN_HELP
GROUP BY WAHLKREIS, JAHR, PARTEI),

SPERRKLAUSELUNTERSCHREITER AS (
SELECT P.WAHLKREIS AS WAHLKREIS, P.JAHR AS JAHR, P.PARTEI AS PARTEI, P.PARTEIGESAMTSTIMMEN AS PARTEIGESAMTSTIMMEN
FROM WAHLKREISGESAMTSTIMMEN W JOIN WAHLKREISPARTEIGESAMTSTIMMEN P ON ((W.WAHLKREIS=P.WAHLKREIS) AND (W.JAHR = P.JAHR))
WHERE (P.PARTEIGESAMTSTIMMEN * 100)/W.GESAMTSTIMMEN < 5),

PARTEIEN_NACH_KLAUSEL AS (
SELECT WAHLKREIS, JAHR, PARTEI
FROM (SELECT *, 1 AS FLAG FROM WAHLKREISPARTEIGESAMTSTIMMEN UNION ALL SELECT *, 2 AS FLAG FROM SPERRKLAUSELUNTERSCHREITER)
GROUP BY WAHLKREIS, JAHR, PARTEI, PARTEIGESAMTSTIMMEN
HAVING SUM(FLAG)=2),

KANDIDATENSIEGERPUNKTE AS (
SELECT A.STIMMKREIS, A.JAHR, MAX(A.ANZAHLERSTSTIMMEN) AS SIEGERPUNKTE
FROM ((AGGREGATKANDIDATERSTSTIMMEN A JOIN WIS.KANDIDAT K ON ((K.JAHR = A.JAHR) AND (K.ID = A.KANDIDAT))) JOIN PARTEIEN_NACH_KLAUSEL P ON ((P.PARTEI = K.PARTEI) AND (K.JAHR = P.JAHR)))
GROUP BY A.STIMMKREIS, A.JAHR)

SELECT A.STIMMKREIS AS STIMMKREIS, A.JAHR AS JAHR, A.KANDIDAT AS SIEGER, S.SIEGERPUNKTE AS SIEGERPUNKTE
FROM AGGREGATKANDIDATERSTSTIMMEN A JOIN KANDIDATENSIEGERPUNKTE S ON ((A.STIMMKREIS = S.STIMMKREIS) AND (S.SIEGERPUNKTE = A.ANZAHLERSTSTIMMEN) AND (A.JAHR = S.JAHR))
