SELECT P.NAME AS PARTEI, P.ABKUERZUNG AS PARTEI_ABKUERZUNG, K.VORNAME AS KANDIDAT_VORNAME, K.NACHNAME AS KANDIDAT_NACHNAME, WZE.KANDIDATPOS AS LISTENPOSITION
FROM WIS.WAHLZETTEL_ERSTSTIMME WZE JOIN WIS.KANDIDAT K ON WZE.KANDIDAT=K.ID AND WZE.JAHR=K.JAHR
    JOIN WIS.PARTEI P ON K.PARTEI=P.ID
WHERE WZE.STIMMKREIS={{STIMMKREIS}} AND WZE.JAHR={{JAHR}}
ORDER BY WZE.KANDIDATPOS
