SELECT P.NAME AS PARTEI, P.ABKUERZUNG AS PARTEI_ABKUERZUNG, K.VORNAME AS KANDIDAT_VORNAME, K.NACHNAME AS KANDIDAT_NACHNAME, WZZ.KANDIDATPOS AS LISTENPOSITION
FROM WIS.WAHLZETTEL_ZWEITSTIMME WZZ JOIN WIS.KANDIDAT K ON WZZ.KANDIDAT=K.ID AND WZZ.JAHR=K.JAHR
    JOIN WIS.PARTEI P ON K.PARTEI=P.ID
WHERE WZZ.STIMMKREIS={{STIMMKREIS}} AND WZZ.JAHR={{JAHR}}
