CREATE VIEW AGGREGAT_ZWEITSTIMMEKANDIDAT (KANDIDAT, STIMMKREIS, JAHR, STIMMEN)
AS 

SELECT KANDIDAT, STIMMKREIS, JAHR, COUNT(*) AS STIMMEN
FROM WIS.ZWEITSTIMMEKANDIDAT
GROUP BY KANDIDAT, JAHR, STIMMKREIS

WITH DYNAMIC CACHE;
