CREATE VIEW WIS.AGGREGAT_ERSTSTIMME (KANDIDAT, STIMMKREIS, JAHR, STIMMEN)
AS 

SELECT KANDIDAT, STIMMKREIS, JAHR, COUNT(*) AS STIMMEN
FROM WIS.ERSTSTIMME 
GROUP BY KANDIDAT, JAHR, STIMMKREIS

WITH DYNAMIC CACHE;
