version: '3'

services:
  backend:
    build: backend
    image: wis-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
  frontend:
    build: web
    image: wis-frontend
    environment:
      - PORT=80
      - BACKEND_URL=http://backend:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
